# Generated by Django 4.2.6 on 2023-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=250, verbose_name='тема')),
                ('count_solutions', models.IntegerField(blank=True, default=0, null=True, verbose_name='количество решений задач')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('numbers', models.CharField(max_length=50, verbose_name='номер контеста')),
                ('index', models.CharField(blank=True, max_length=20, null=True, verbose_name='индекс задачи')),
                ('complexity', models.CharField(max_length=100, verbose_name='сложность')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
