# Generated by Django 4.2.6 on 2023-10-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number_contest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='номер контеста'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numbers',
            field=models.CharField(max_length=50, verbose_name='номер задачи'),
        ),
    ]
