# Generated by Django 4.2.6 on 2023-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_number_contest_alter_task_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='numbers',
            field=models.CharField(max_length=50, unique=True, verbose_name='номер задачи'),
        ),
    ]
